import Head from "next/head";
import { ApolloProvider } from "@apollo/client";
import client from '../apollo/client';
import { useUserInfo } from "../hooks/user";
import styles from "../styles/Home.module.scss";
import Main from "./main";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WithPet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ApolloProvider client={client}>
          <Main />
        </ApolloProvider>
      </main>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const userInfo = useUserInfo(ctx);
  if (!userInfo) {
    return {
      redirect: {
        permanent: false,
        destination: "/login",
      },
      props: {},
    }
  }
  return {
    props: {},
  }
}

export default Home;
